@extends('layouts.app')

@section('title', 'Disclaimer — WebCheckApp')
@section('meta_description', 'Read the WebCheckApp disclaimer before using our free website security scanner.')

@section('content')
<div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">

    <div class="mb-10">
        <h1 class="text-3xl font-bold text-white mb-3">Disclaimer</h1>
        <p class="text-gray-400">Last updated: {{ date('F j, Y') }}</p>
    </div>

    <div class="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 leading-relaxed">

        <section>
            <h2 class="text-xl font-semibold text-white mb-3">Informational purposes only</h2>
            <p>WebCheckApp provides automated security and performance scans for informational purposes only. The results, scores and recommendations shown are generated by automated checks and do not constitute professional security advice, a security audit, or a penetration test.</p>
            <p class="mt-3">You should not rely solely on WebCheckApp results to determine whether a website is secure. A passing score does not guarantee that a website is free from vulnerabilities. Critical security assessments should always be performed by qualified security professionals.</p>
        </section>

        <section>
            <h2 class="text-xl font-semibold text-white mb-3">Limitation of liability</h2>
            <p>WebCheckApp and its operator, <a href="https://www.budgetpixels.nl" target="_blank" rel="noopener noreferrer" class="text-indigo-400 hover:text-indigo-300">BudgetPixels.nl</a>, accept no liability for:</p>
            <ul class="list-disc list-inside mt-3 space-y-2 text-gray-400">
                <li>Inaccurate, incomplete or outdated scan results</li>
                <li>Any damage or loss resulting from actions taken based on scan results</li>
                <li>Security incidents that occur despite a positive scan result</li>
                <li>Temporary unavailability of the scanning service</li>
                <li>Results obtained for websites operated by third parties</li>
            </ul>
        </section>

        <section>
            <h2 class="text-xl font-semibold text-white mb-3">Accuracy of results</h2>
            <p>Our scanner performs automated checks based on publicly accessible information (HTTP headers, DNS records, SSL certificate details). The following limitations apply:</p>
            <ul class="list-disc list-inside mt-3 space-y-2 text-gray-400">
                <li>Mixed content detection only covers HTML source — dynamically loaded resources are not checked</li>
                <li>DNSSEC verification may not always be conclusive due to DNS resolver limitations</li>
                <li>Response times are measured from our scanner server and may differ from real-world user experience</li>
                <li>Not all security vulnerabilities can be detected through automated external scanning</li>
            </ul>
        </section>

        <section>
            <h2 class="text-xl font-semibold text-white mb-3">Responsible use</h2>
            <p>By using WebCheckApp you agree that you will only scan websites that you own or have explicit authorisation to test. Scanning third-party websites without permission may violate applicable laws. WebCheckApp and BudgetPixels.nl bear no responsibility for misuse of this tool.</p>
        </section>

        <section>
            <h2 class="text-xl font-semibold text-white mb-3">External links</h2>
            <p>WebCheckApp may contain links to external websites. We have no control over the content or availability of those sites and accept no responsibility for them.</p>
        </section>

        <section>
            <h2 class="text-xl font-semibold text-white mb-3">Contact</h2>
            <p>Questions about this disclaimer? Contact us via <a href="https://www.budgetpixels.nl" target="_blank" rel="noopener noreferrer" class="text-indigo-400 hover:text-indigo-300">budgetpixels.nl</a>.</p>
        </section>

    </div>
</div>
@endsection
